### MULTIPLE LINEAR REGRESSION

In [43]:
import pandas as pd
import numpy as np

In [44]:
df=pd.read_csv(r"C:\Users\sweet\OneDrive\Documents\GitHub\MACHINE LEARNING\archive (3)\teslay.csv")
df.columns
df.shape
df

,year,km,color,price
0,2025,69000.0,White,2095000
1,2024,28500.0,Black,2280000
2,2024,50000.0,White,2090000
3,2024,42000.0,White,2180000
4,2024,15000.0,White,2300000
...,...,...,...,...
250,2025,24000.0,Black,2390000
251,2024,29000.0,White,2185000
252,2025,19800.0,White,2305000
253,2024,16000.0,White,2250000


In [45]:
df["color"].unique()

array(['White', 'Black', 'Blue', 'Silver Gray', 'Burgundy', 'Smoke Gray',
       'Gray', 'Navy Blue', 'Red'], dtype=object)

##### convert string to integer by providing values from 0 to n

In [46]:
colors = df["color"].unique()

for num, color in enumerate(colors):
    df["color"] = df["color"].replace(color, num)

df["color"]

C:\Users\sweet\AppData\Local\Temp\ipykernel_17432\410810143.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["color"] = df["color"].replace(color, num)


0      0
1      1
2      0
3      0
4      0
      ..
250    1
251    0
252    0
253    0
254    0
Name: color, Length: 255, dtype: int64

In [47]:
print(colors)

['White' 'Black' 'Blue' 'Silver Gray' 'Burgundy' 'Smoke Gray' 'Gray'
 'Navy Blue' 'Red']


##### Multiple input features

In [48]:
print(type(df["color"][0]))
print(type(df["km"][0]))
print(type(df["year"][0]))

<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.int64'>


In [49]:
df['year']

0      2025
1      2024
2      2024
3      2024
4      2024
       ... 
250    2025
251    2024
252    2025
253    2024
254    2024
Name: year, Length: 255, dtype: int64

##### Here we use normalization technique for convert them all into range 0 to 1 for optimization

In [50]:
# x=np.array([df["year"],df["km"],df["color"]])

temp = df["year"].astype("float")
temp2 = df["color"].astype("float")

x = np.array((temp, df["km"], temp2))
print(x.shape)
# Min-Max Normalization per row (feature)
print('x', x[::, 0])
x_min = x.min(axis=1, keepdims=True)
print('x_min', x_min)
x_max = x.max(axis=1, keepdims=True)
print('x_max', x_max)
x_scaled = (x - x_min) / (x_max - x_min)

# Normalize your target array as well to prevent huge gradient steps
y = np.array(df["price"], dtype=float)
y_min = y.min()
y_max = y.max()
y_scaled = (y - y_min) / (y_max - y_min)

print(x_scaled.shape)
print(y_scaled.shape)

(3, 255)
x [ 2025. 69000.     0.]
x_min [[2024.]
 [6001.]
 [   0.]]
x_max [[2.025e+03]
 [1.100e+05]
 [8.000e+00]]
(3, 255)
(255,)


In [51]:
y=np.array(df["price"])
y

array([2095000, 2280000, 2090000, 2180000, 2300000, 2155000, 2300000,
       2280000, 2350000, 2075000, 2290000, 2325000, 2239750, 2165000,
       2209750, 2225000, 2395000, 1835000, 2125000, 2700000, 2300000,
       2300000, 1880000, 2140000, 2280000, 2120000, 1995000, 2185000,
       2390000, 2159000, 2125000, 2300000, 2225000, 2099000, 2400000,
       2199000, 1899750, 2225000, 2280000, 1950000, 2250000, 2435500,
       2225000, 2150000, 2275000, 2210000, 1990000, 2189000, 2125000,
       2190000, 2350000, 2250000, 2490000, 2325000, 2435000, 2110000,
       2495000, 2249990, 2098500, 2220000, 2251000, 2195000, 2250000,
       2150000, 2110000, 2185000, 2050000, 2336000, 2320000, 2300000,
       2329000, 2200000, 2185000, 2185000, 2400000, 2275000, 2180000,
       2390000, 2350000, 2450000, 2165000, 2189750, 2125000, 2225000,
       2230000, 2085000, 2160000, 2065000, 2200000, 2135000, 2280000,
       2490000, 2199900, 2240000, 2185000, 2270000, 2010000, 2150000,
       2455000, 2285

##### Full is used to fill values based on its length

In [52]:
w=np.full(len(x), 0.5)
b=0.5

##### Perdict Using Dot product 

In [53]:
def predict(x,y,w,b):
    return np.dot(w,x) +b

In [54]:
y_pred=predict(x,y,w,b)
y_pred

array([35513. , 15263. , 26012.5, 22012.5,  8512.5, 19175.5,  9263.5,
        7762.5, 18014. , 17012.5,  8287.5, 16514.5,  8512.5, 17513.5,
       20546. , 23013.5,  5513. , 14012.5, 28512.5,  4016. ,  9513. ,
       21762.5, 24762.5, 37513.5, 15862.5, 23512.5, 32012.5, 14013. ,
        7763. , 16013. , 18777.5,  7412.5, 17480. , 27512.5, 16012.5,
       15262.5,  9512.5, 14012.5, 16013. , 20012.5, 11262.5, 11012.5,
       13853. , 24013.5, 13012.5, 21763.5, 20012.5, 23691. , 18012.5,
       19012.5, 14512.5, 10013. ,  4018. , 19262.5, 13262.5, 20502.5,
       12513. , 17512.5, 31762.5, 12012.5,  8548.5, 15762.5, 12512.5,
       33012.5, 17512.5, 13362.5, 23012.5,  7762.5, 20512.5, 10013.5,
        9512.5, 12012.5, 26512.5, 25512.5,  9263. ,  6074.5, 21763.5,
        4013. , 10313. ,  8513. , 16512.5, 14762.5, 17938. , 15013.5,
       13727.5, 32512.5, 17512.5, 22762.5, 17512.5, 25762.5, 15663. ,
        4013. , 20513. , 18012.5, 13512.5, 11016. , 38512.5, 20262.5,
       20516. ,  850

##### Error

In [55]:
def error(y,y_pred):
    return y-y_pred

In [56]:
err=error(y,y_pred)
err

array([2059487. , 2264737. , 2063987.5, 2157987.5, 2291487.5, 2135824.5,
       2290736.5, 2272237.5, 2331986. , 2057987.5, 2281712.5, 2308485.5,
       2231237.5, 2147486.5, 2189204. , 2201986.5, 2389487. , 1820987.5,
       2096487.5, 2695984. , 2290487. , 2278237.5, 1855237.5, 2102486.5,
       2264137.5, 2096487.5, 1962987.5, 2170987. , 2382237. , 2142987. ,
       2106222.5, 2292587.5, 2207520. , 2071487.5, 2383987.5, 2183737.5,
       1890237.5, 2210987.5, 2263987. , 1929987.5, 2238737.5, 2424487.5,
       2211147. , 2125986.5, 2261987.5, 2188236.5, 1969987.5, 2165309. ,
       2106987.5, 2170987.5, 2335487.5, 2239987. , 2485982. , 2305737.5,
       2421737.5, 2089497.5, 2482487. , 2232477.5, 2066737.5, 2207987.5,
       2242451.5, 2179237.5, 2237487.5, 2116987.5, 2092487.5, 2171637.5,
       2026987.5, 2328237.5, 2299487.5, 2289986.5, 2319487.5, 2187987.5,
       2158487.5, 2159487.5, 2390737. , 2268925.5, 2158236.5, 2385987. ,
       2339687. , 2441487. , 2148487.5, 2174987.5, 

##### Loss 

In [57]:
def MSE(err):
    return np.mean((err**2))

In [58]:
mse=MSE(err)
print(mse)

5000949080207.126


#### Gradient Descent Optimization

In [59]:

def grad(x,y,w,b):
    n=x.shape[1]
    y_pred=predict(x,y,w,b)
    err=error(y,y_pred)
   
    dw = (-2/n) * np.dot(x, (err))
    db = (-2/n) * (np.sum(err))


    return dw,db




##### Update Weight and bias

In [60]:
lr=0.01   #Learning rate 
def update(w,b,dw,db,lr):
    w=w- lr*dw
    b=b- lr*db
    return w,b

In [61]:
epochs= 3000
for i in range(epochs):
    
    y_pred = predict(x_scaled, y_scaled, w, b)
    
    err = error(y_scaled, y_pred)
    
    mse = MSE(err)
    
    dw, db = grad(x_scaled, y_scaled, w, b)
    

    w, b = update(w, b, dw, db, lr)
    
    if i % 100 == 0:
        print(f"Epoch {i} -> Loss (MSE): {mse:.6f} | Weights: {w} | Bias: {b}")
# print(y)
# print(y_pred)


Epoch 0 -> Loss (MSE): 0.240901 | Weights: [0.49704927 0.49769963 0.49892543] | Bias: 0.49127600178793546
Epoch 100 -> Loss (MSE): 0.033881 | Weights: [0.34381572 0.39510532 0.44320203] | Bias: 0.16173752394525512
Epoch 200 -> Loss (MSE): 0.027763 | Weights: [0.28413581 0.36520123 0.41802993] | Bias: 0.14388373609432284
Epoch 300 -> Loss (MSE): 0.025107 | Weights: [0.24541829 0.34207882 0.39695138] | Bias: 0.1562382314225922
Epoch 400 -> Loss (MSE): 0.023198 | Weights: [0.21700778 0.31926303 0.37726817] | Bias: 0.16982966271123418
Epoch 500 -> Loss (MSE): 0.021717 | Weights: [0.19558965 0.29639384 0.35873176] | Bias: 0.18206042215237722
Epoch 600 -> Loss (MSE): 0.020506 | Weights: [0.1792233  0.273659   0.34131866] | Bias: 0.19298572313645687


Epoch 700 -> Loss (MSE): 0.019477 | Weights: [0.16654932 0.25123515 0.32500725] | Bias: 0.20285313420469403
Epoch 800 -> Loss (MSE): 0.018579 | Weights: [0.15658593 0.22924822 0.309762  ] | Bias: 0.21186758370700148
Epoch 900 -> Loss (MSE): 0.017783 | Weights: [0.14862054 0.20778303 0.29553715] | Bias: 0.22018377169440828
Epoch 1000 -> Loss (MSE): 0.017068 | Weights: [0.1421352  0.18689429 0.28228092] | Bias: 0.22791778244923422
Epoch 1100 -> Loss (MSE): 0.016422 | Weights: [0.13675308 0.16661508 0.26993854] | Bias: 0.23515730891370873
Epoch 1200 -> Loss (MSE): 0.015836 | Weights: [0.13219967 0.14696293 0.25845446] | Bias: 0.24196926236017155
Epoch 1300 -> Loss (MSE): 0.015303 | Weights: [0.12827466 0.1279443  0.24777371] | Bias: 0.2484053175358031
Epoch 1400 -> Loss (MSE): 0.014817 | Weights: [0.12483161 0.10955779 0.23784293] | Bias: 0.2545059432930088
Epoch 1500 -> Loss (MSE): 0.014373 | Weights: [0.12176317 0.09179648 0.22861092] | Bias: 0.26030333320695354
Epoch 1600 -> Loss (MSE)

In [66]:
# 1. Raw Test Sample
test_raw = np.array([[2025.0], [69000.0], [0.0]])

# 2. Scale using original training parameters (x_min, x_max)
test_scaled = (test_raw - x_min) / (x_max - x_min)
test_scaled = test_scaled.flatten() # Flatten to 1D array of shape (3,)

# 3. Predict scaled target price
scaled_pred = predict(test_scaled, None, w, b)

# 4. Invert scaling to read the real price in currency
final_price = (scaled_pred * (y_max - y_min)) + y_min
print(f"\nPredicted Car Price: {final_price:.2f}")
print(f"Actual Car Price: {y[0]}")


Predicted Car Price: 2271315.70
Actual Car Price: 2095000


In [68]:
print(x[::, 0])
print(y[0])

[ 2025. 69000.     0.]
2095000


In [69]:
predict(np.array([2025, 69000, 0]),y,w,b)

np.float64(-7371.996125965296)